# Generated by Django 3.1.5 on 2021-01-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snipe_model_id', models.IntegerField()),
                ('model_name', models.CharField(max_length=250)),
                ('model_manufacturer_name', models.CharField(max_length=250)),
                ('model_number', models.CharField(max_length=250)),
                ('model_category', models.CharField(max_length=250)),
                ('model_count', models.IntegerField()),
                ('model_deleted', models.BooleanField(default=False)),
                ('model_min_qty', models.PositiveIntegerField(null=True, verbose_name='minimum quantity')),
            ],
        ),
        migrations.CreateModel(
            name='Asset_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snipe_model_id', models.IntegerField()),
                ('model_name', models.CharField(max_length=250)),
                ('model_manufacturer_name', models.CharField(max_length=250)),
                ('model_number', models.CharField(max_length=250)),
                ('model_category', models.CharField(max_length=250)),
                ('model_location', models.CharField(max_length=250)),
                ('model_custom_fields', models.TextField()),
            ],
        ),
    ]
