# Generated by Django 3.1.5 on 2021-01-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('min_asset_levels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset_models',
            name='model_deleted',
        ),
    ]
