# Generated by Django 3.1.5 on 2021-01-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('min_asset_levels', '0002_remove_asset_models_model_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_models',
            name='model_min_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='minimum quantity'),
        ),
    ]
