# Generated by Django 3.1.5 on 2021-01-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('min_asset_levels', '0003_auto_20210122_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset_report',
            name='model_category',
        ),
        migrations.RemoveField(
            model_name='asset_report',
            name='model_manufacturer_name',
        ),
        migrations.RemoveField(
            model_name='asset_report',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='asset_report',
            name='model_number',
        ),
        migrations.AddField(
            model_name='asset_models',
            name='model_count_RTD',
            field=models.IntegerField(default=0),
        ),
    ]
