# Generated by Django 3.1.5 on 2021-01-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('min_asset_levels', '0004_auto_20210122_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_report',
            name='model_asset_id',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
