# Generated by Django 3.1.5 on 2021-02-03 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('min_asset_levels', '0006_auto_20210203_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset_report',
            old_name='snipe_model_id',
            new_name='asset_models',
        ),
    ]
