# Generated by Django 3.1.5 on 2021-02-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('min_asset_levels', '0007_auto_20210203_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset_report',
            old_name='asset_models',
            new_name='snipe_model_id',
        ),
    ]
