# Generated by Django 3.1.5 on 2021-02-03 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('min_asset_levels', '0010_auto_20210203_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset_report',
            name='snipe_model_id',
        ),
        migrations.AddField(
            model_name='asset_report',
            name='asset_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='min_asset_levels.asset_models'),
            preserve_default=False,
        ),
    ]
